language: python

matrix:
  include:
    - name: "try anaconda under linux"
      env:
        - PATH="$HOME/miniconda3/bin:$PATH"
      before_install:
        - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda3.sh; bash /tmp/miniconda3.sh -b -p $HOME/miniconda3
      script:
      - python --version
      - pip --version
