services:
  - postgresql
  - mysql
  - mongodb

matrix:
  include:
    - name: "try services under windows"
      os: "windows"
      script:
      - set
      
      - cmd.exe /C '"C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Auxiliary/Build/vcvarsall.bat" amd64 && cl'
      - cmd.exe /C '"C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Auxiliary/Build/vcvarsall.bat" amd64 && msbuild /version'

      - netstat -ant