language: python
dist: xenial
python: 3.7
services:
  - mysql
  - postgresql
  - mongodb

matrix:
  include:
    - name: "linux"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
        env:
          - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      script:
        - python -c "import platform; print(platform.uname())"
        - python --version
        - pip --version
        - netstat -anpt
        - gcc --version
        - g++ --version
        - g++-8 --version
