language: python

dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)

python:
  - "3.7"

matrix:
  include:
    - name: "linux"
      script:
        - python -m pip install --upgrade pip wheel setuptools
        - pip install ibapi-9.75.1-py3-none-any.whl
        - python -c "import platform; print(platform.uname())"
        - python --version
        - pip --version
