language: python

matrix:
  include:
    - name: "linux"
      script:
        - pip install ibapi-9.75.1-py3-none-any.whl
        - python -c "import platform; print(platform.uname())"
        - python --version
        - pip --version
