language: python

dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)

python:
  - "3.7"

matrix:
  include:
  
    # check gcc and g++ version
    - before_install:
        # C++17
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
      install:
        # C++17
        - sudo apt-get install -qq gcc-8 g++-8 mlocate
        - sudo update-alternatives --install /usr/bin/g++ /usr/bin/gcc g++ gcc /usr/bin/g++-8 /usr/bin/gcc-8 90
        - sudo updatedb
      script:
        - gcc --version
        - g++ --version
        - for g in `locate gcc |grep gcc$`; do [ -f $g ] && echo $g && $g --version;  done
        - for g in `locate g++ |grep g++$`; do [ -f $g ] && echo $g && $g --version;  done
