services:
  - mysql
  - postgresql
  - mongodb

matrix:
  include:
    - name: "osx"
      os: osx
      script:
        - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 100
        - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 100
        - python -c "import platform; print(platform.uname())"
        - python --version
        - pip --version
        - netstat -anpt
