services:
  - mysql
  - postgresql
  - mongodb

matrix:
  include:
    - name: "osx"
      os: osx
      script:
        - python -c "import platform; print(platform.uname())"
        - python --version
        - pip --version
        - pip list
        - python3 --version
        - pip3 --version
        - pip3 list
        - netstat -anp
