language: python

dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)

python:
  - "3.7"
    
matrix:
  include:
    - name: "linux"
      script:
        - pip install ibapi-9.75.1-py3-none-any.whl
        - pip install -r requirements.txt
        - python -c "import platform; print(platform.uname())"
        - python -c "import talib; import ibapi"

