services:
  - mysql
  - postgresql
  - mongodb
dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)

matrix:
  include:
    - name: "osx"
      os: osx
      script:
        - python -c "import platform; print(platform.uname())"
        - python --version
        - pip --version
        - pip list
        - python -m pip install --upgrade pip setuptools
        - python -m pip list
        - python3 --version
        - pip3 --version
        - pip3 list
        - python3 -m pip list
        - python3 -m pip install --upgrade pip setuptools
        - netstat -an
