language: python
services:
  - mysql
  - postgresql
  - mongodb

matrix:
  include:
    - name: "linux"
      script:
        - python -c "import platform; print(platform.uname())"
        - python --version
        - pip --version
        - netstat -anpt
